import React from 'react'
import Head from 'next/head';
import PageMain from './components/pageMain';
import BottomBar from './components/bottomBar';
import CompanyAddressForm from './components/companyAddressForm';
import 'antd/dist/antd.css';

export default function CompanyAddress() {
    return (
        <>
        <div className="page_container">
                <Head>
                    <title>Spyidol | Endereço</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <PageMain FormComponent={<CompanyAddressForm />} />
                <BottomBar />
            </div >
            
        </>
    )
}
