import React, { useState, useEffect } from 'react';
import Image from 'next/image'
import Head from 'next/head'
import { Typography, Button, Form, Input, Row, Col, Dropdown, Menu, Space, Drawer } from "antd"
import { DownOutlined } from '@ant-design/icons';
import 'antd/dist/antd.css';

function Login() {

    const { Title, Text, Link } = Typography;
    const [form] = Form.useForm();
    const [open, setOpen] = useState(false);
    const [feildsValue, setFeildsValue] = useState({
        email: "",
        password: ""
    });


    const submitLoginForm = async (e) => {
        e.preventDefault();
        console.log(feildsValue);
        const values = await form.validateFields();
        try {
            console.log('Success:', values);
        } catch (errorInfo) {
            console.log('Failed:', errorInfo);
        }
        if (feildsValue.email || feildsValue.password !== "") {
            // const result = await fetch("api" , {
            //     "Content-Type" : "application/json",
            //     "method" : "POST",
            //     "body" : JSON.stringify(feildsValue)
            // });
            // const res = await result.json();
        }
    };


    // useEffect(()=> {
    //     console.log(feildsValue);
    // } , [feildsValue])

    const showDrawer = () => {
        setOpen(true);
    };
    const onClose = () => {
        setOpen(false);
    };




    const menu = (
        <Menu
            items={[
                {
                    key: '1',
                    label: (
                        <a href="#">
                            A SpyIdol
                        </a>
                    ),
                },
                {
                    key: '2',
                    label: (
                        <a href="#">
                            Embaixadores
                        </a>
                    ),
                },
                {
                    key: '3',
                    label: (
                        <a href="#">
                            Afiliados
                        </a>
                    ),
                },
                {
                    key: '4',
                    label: (
                        <a href="#">
                            Nossa loja
                        </a>
                    ),
                },
                {
                    key: '5',
                    label: (
                        <a href="#">
                            Suporte
                        </a>
                    ),
                },
                {
                    key: '6',
                    label: (
                        <a href="#">
                            FAQ
                        </a>
                    ),
                },
                {
                    key: '7',
                    label: (
                        <a href="#">
                            Termos & Condições
                        </a>
                    ),
                },
                {
                    key: '8',
                    label: (
                        <a href="#">
                            Privacidade
                        </a>
                    ),
                }
            ]}
        />
    );



    const languages = (
        <Menu
            items={[
                {
                    key: '1',
                    label: (
                        <a href="#">
                            English
                        </a>
                    ),
                },
                {
                    key: '2',
                    label: (
                        <a href="#">
                            Arabic
                        </a>
                    ),
                },
                {
                    key: '3',
                    label: (
                        <a href="#">
                            German
                        </a>
                    ),
                },
            ]}
        />
    );

    const updateFeildValue = (e) => {
        setFeildsValue({ ...feildsValue, [e.target.name]: e.target.value });
    }

    return (
        <>
            <div className="page_container">
                <Head>
                    <title>Spyidol | Login</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <div className="main">
                    <div className="formouter">
                        <div className="formcover">
                            <div className="logo_image">
                                <Image src="/images/spyidol-logo.png" layout='fill' alt='logo' className="image" />
                            </div>
                            <div className="form_body">
                                <Title level={2} className="form_heading">
                                    Entre com sua conta
                                </Title>

                                <Form
                                    form={form}
                                    className="login_form"
                                    name="login_form"
                                    layout="vertical"
                                    onSubmitCapture={(e) => {submitLoginForm(e)}}
                                    initialValues={{
                                        remember: true,
                                    }}
                                >
                                    <Form.Item label="E-mail ou nome de usuário" style={{ marginBottom: "0", marginLeft: "13px", fontFamily: "WorkSans-SemiBold" }}>
                                        <Form.Item
                                            initialValue={feildsValue.email}
                                            style={{ marginLeft: "-13px", fontFamily: "WorkSans-Normal" }}
                                            name="email"
                                            rules={[{ required: true, message: 'Por favor, digite o e-mail ou nome de usuário' }]}>
                                            <Input size="large" name="email" onChange={(e) => { updateFeildValue(e) }} value={feildsValue.email} placeholder="Digite E-mail ou nome de usuário" />
                                        </Form.Item>
                                    </Form.Item>

                                    <Form.Item label="Senha" style={{ marginBottom: "0", marginLeft: "13px", fontFamily: "WorkSans-SemiBold" }}>
                                        <Form.Item
                                            initialValue={feildsValue.password}
                                            rules={[{ required: true, message: 'Por favor, digite a senha' }]}
                                            style={{ marginLeft: "-13px", fontFamily: "WorkSans-Normal" }}
                                            name="password"
                                        >
                                            <Input size="large" name="password" placeholder="Digite Senha" onChange={(e) => { updateFeildValue(e) }} value={feildsValue.password} />
                                        </Form.Item>
                                    </Form.Item>

                                    <Form.Item className='fpassword_link' style={{ textAlign: "end" }}>
                                        <Link className="forgetPassLink" href="forget_password">Esqueceu sua senha?</Link>
                                    </Form.Item>

                                    <Form.Item style={{ marginBottom: "0" }}>
                                        <Button size="large" htmlType='submit' className="form_submit_btn" type="primary">Entrar</Button>
                                    </Form.Item>

                                </Form>





                            </div>
                            <div className="loginFormFooter">
                                <Text>Eu não tenho conta? <Link href="#" className="link_underline">Inscrever-se</Link></Text>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="bottom_bar">
                    <Row className="footer_menu_row" justify="space-between" align='middle' style={{ width: "100%" }}>
                        <Col>
                            <div className="language">
                                <div className="glob_icon">
                                    <Image src='/images/language_icon.png' alt='language' height={20} width={20} />
                                </div>
                                <div className="select_language">
                                    <Space>
                                        <Dropdown overlay={languages}>
                                            <Button ghost style={{ color: "white", backgroundColor: "transparent", border: "none" }}>
                                                <Space>
                                                    Português
                                                    <DownOutlined />
                                                </Space>
                                            </Button>
                                        </Dropdown>
                                    </Space>
                                </div>
                            </div>
                        </Col>
                        <Col flex="1 0 70%" lg={16} md={0} sm={0} xs={0}>
                            <div className="menu_bar">
                                <Link href="#" className="link_white">A SpyIdol</Link>
                                <Link href="#" className="link_white">Embaixadores</Link>
                                <Link href="#" className="link_white">Afiliados</Link>
                                <Link href="#" className="link_white">Nossa loja</Link>
                                <Link href="#" className="link_white">Suporte</Link>
                                <Link href="#" className="link_white">FAQ</Link>
                                <Link href="#" className="link_white">Termos & Condições</Link>
                                <Link href="#" className="link_white">Privacidade</Link>
                            </div>
                        </Col>
                        <Col>
                            <Text style={{ fontSize: "15px", color: "white" }}>@ 2022 SpyIdol</Text>
                        </Col>
                        <Col lg={0} md={4} xs={1} sm={3}>
                            <nav className="navbar">
                                <Image src="/images/hamburger.png" alt="menu_icon" height="15" width="15"
                                    className="menu"
                                    onClick={showDrawer}
                                />
                                <Drawer
                                    style={{ textAlign: "center", backgroundColor: "transparent" }}
                                    placement="left"
                                    closable={false}
                                    onClose={onClose}
                                    open={open}
                                    key="left"
                                >
                                    <div className="menu_box">
                                        <Image src="/images/spyidol-logo.png" className="image" alt="logo" height="60" width="200" />
                                        {menu}
                                    </div>
                                    <div className="sidebar_footer">
                                        <Text style={{ fontSize: "15px" }}>@ 2022 SpyIdol</Text>
                                    </div>
                                </Drawer>
                            </nav>
                        </Col>
                    </Row>
                </div>
            </div >
        </>
    )
}

export default Login;