import React from 'react'
import Head from 'next/head';
import PageMain from './components/pageMain';
import BottomBar from './components/bottomBar';
import RegisterForm from './components/registerForm';
import 'antd/dist/antd.css';

export default function Register() {
    return (
        <>
        <div className="page_container">
                <Head>
                    <title>Spyidol | Crie sua conta</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <PageMain FormComponent={<RegisterForm />}  footerText="Já possui conta?" footerLink="Entrar"/>
                <BottomBar />
            </div >
            
        </>
    )
}
